### ISSUE TITLE
[Bug] Operation not permitted when VIDEO_PATHS is drive letter

### ISSUE THREAD

**Issue by yur1xpp** [boi123212321/porn-vault#560] opened 2020-05-16 09:23 UTC
**Describe the bug**
It seems like it try to access system files like "System Volume Information" and throw an error. Is there a way to exclude those folders?

**To Reproduce**
1. Add drive letter (`D:\\`) as your VIDEO_PATHS
2. Run

**Expected behavior**
Recursively scan all the videos in that drive

**Screenshots**
![image](https://user-images.githubusercontent.com/34767893/82116126-e2dac500-9799-11ea-9dca-f71bded2cd6b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 1909
 - Browser: Firefox
 - Version: latest

**Comment by boi123212321** [comment] 2020-05-16 10:55
Add a list of regular expressions into EXCLUDE_FILES in your config. It works essentially like a blacklist, so
```
EXCLUDE_FILES: ["System Volume"]
```
should ignore that folder.

**Comment by yur1xpp** [comment] 2020-05-18 13:17
As discussed in Discord and for tracking of bug, the bug introduced after added "System Volume" into exclude:
![image](https://user-images.githubusercontent.com/34767893/82217332-dba7e880-994c-11ea-9457-9afa90972daf.png)

**Comment by boi123212321** [comment] 2020-05-18 14:40
FWIW using a drive letter may not be supported, I'm not sure.

**Comment by yur1xpp** [comment] 2020-05-19 07:51
Perhaps support for wildcard path maybe? Like `D:\\Folder*`

**Comment by boi123212321** [comment] 2020-05-19 12:50
@yur1xpp `D:\\Folder`
It will walk recursively through that folder

**Comment by yur1xpp** [comment] 2020-05-20 08:20
Yeah, but If I have a directories,
----Folder123
----Folder456
----Folder789
---and so on
I guess I would need to input all those folders manually no?

**Comment by boi123212321** [comment] 2020-05-20 11:58
@yur1xpp Yeah, I would recommend having one folder where you put your folders in

**Comment by leadwolf** [comment] 2020-05-23 16:45
Fwiw, I cannot reproduce the exclusion not working on 1768066fac4c05f3092b289b19a9be0c08eeace7.
I don't have a "System Volume Information" folder, but I created a root `C:\pv` folder in which i created a `System Volume Information` folder, and denied permissions to it for all users. I can confirm the program errors out and hangs when attemping to get its details.
But with a simple `"EXCLUDE_FILES": ["System Volume"]`, the program did not even attempt to read it.

**Comment by boi123212321** [comment] 2020-05-24 14:17
I'll close this for now. I can't test stuff for Windows, and hope #588 helps with this as well

**Closed by boi123212321** 2020-05-24 14:17 UTC
Labels: bug, help wanted, windows
