### ISSUE TITLE
[Bug] Duplicate studios

### ISSUE THREAD

**Issue by echo6ix** [boi123212321/porn-vault#658] opened 2020-06-25 00:48 UTC
**Describe the bug**
Creating or editing a studio causes a duplication of the studio in the studio.db

**To Reproduce**
1. Go to Studios
2. Click on the appropriate link to create a studio or edit an existing studio
3. When finished a duplicate entry will be added to the database and this will appear in the UI
4. If editing a studio, each time it is edited the duplication will be incremented by one
5. Closing PV and restarting removes all the duplications 

**Expected behavior**
Non-duplication

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 Server
 - Browser Chrome
 - Version 83

**Comment by boi123212321** [comment] 2020-06-29 13:18
Possibly duplicate of https://github.com/boi123212321/porn-vault/issues/584 ?

**Comment by ciaron88** [comment] 2020-07-01 16:53
I am getting this with movies on 0.22.0 when I edit a movie it creates duplicates.

**Comment by boi123212321** [comment] 2020-07-02 11:53
https://github.com/boi123212321/porn-vault/issues/584#issuecomment-638133680

**Closed** 2020-09-24 14:50 UTC
Labels: bug
