### ISSUE TITLE
[Bug] When adding a new movie, duplicates appear once added.

### ISSUE THREAD

**Issue by OffspringFan88** [boi123212321/porn-vault#584] opened 2020-05-21 11:41 UTC
When adding a new movie in current version porn-vault-0.22-rc.1 duplicates appear even though the movie has only been added once.

This didn't happen in previous versions. 

I've attached screenshots to show what happens.

![unknown](https://user-images.githubusercontent.com/54474989/82555876-8e03c980-9b60-11ea-8d47-49bf64c6bbdd.png)
![Capture](https://user-images.githubusercontent.com/54474989/82556099-fb175f00-9b60-11ea-80a1-f730931a70d5.PNG)

**Comment by boi123212321** [comment] 2020-06-02 14:22
I still cannot reproduce this, also try RC2 first

**Comment by OffspringFan88** [comment] 2020-06-02 14:26
Have you tried it with labels added?

I have labels added to my movies and it does it.

**Comment by johnnyporn88** [comment] 2020-06-02 17:42
It is also happening for studios.

Reproduction steps:
1) Create new movie/studio.
2) Add label to movie scene (which would add it to movie as well) or studio
3) Return to movie/studio page.

That's all.

**Comment by boi123212321** [comment] 2020-06-03 11:24
Should be resolved with https://github.com/boi123212321/gianna/releases/tag/0.2.1

**Closed by boi123212321** 2020-06-03 11:24 UTC
Labels: bug, reproduction needed
